---
DISINTAR:
  TON_PUNKS_COLLECTION_URL: https://beta.disintar.io/collection/UQAo92DYMokxghKcq-CkCGSk_MgXY5Fo1SPW20gkvZl75n1I
  LOAD_TIME: 1.5
  MAX_PRICE: 1500
  CLASS_NAME:
    DIV:
      NFT_CARD_CONTAINER: NFTCard__container___2XJg7
      NFT_CARD_META: NFTCard__meta___8iDmY
      NFT_CARD_PRICE: NFTCard__price___1ZkF5
    H1:
      NFT_CARD_TITLE: NFTCard__title___2oPAP
TON_NFT_TOOLS:
  TON_PUNKS_COLLECTION_URL: https://tonnft.tools/collection/tonpunks
  TON_PUNKS_COLLECTION_URL_WITH_PAGE: https://tonnft.tools/collection/tonpunks?page=
  LOAD_TIME: 1.5
  CLASS_NAME:
    DIV:
      NFT_CARD_CONTAINER: card text-decoration-none nftItemCard
      ATTRIBUTE_VALUE: ms-2 me-auto
      ATTRIBUTE_NAME: fw-bold
    BUTTON:
      MODAL_DIALOG_CLOSE: btn-close btn-sm
    LI:
      ATTRIBUTE_CONTAINER: list-group-item px-2 d-flex justify-content-between align-items-start
      PAGE_ITEM: page-item
    SPAN:
      ATTRIBUTE_SCORE: badge py-2 px-3 bg-teal rounded-pill text-light
    UL:
      PAGINATION: pagination mb-0
  ID:
    SPAN:
      MODAL_RARITY_RANK: modalRarityRank
    U:
      MODAL_RARITY_SCORE: modalRarityScore
    H4:
      MODAL_NAME: modalName
    INPUT:
      MODAL_NFT_ADDRESS: modalNftAddress
    UL:
      MODAL_ATTRIBUTES: modalAttributes